//! Emits Rust source for the analysed blocks.
//!
//! Each block becomes a function `fn b_XXXX(z: &mut Zx) -> bool` that first
//! checks the code bytes it was compiled from are still in memory (so code
//! that is overwritten falls back to the interpreter), then runs the
//! instructions as straight-line Rust, sets `z.pc` and returns `true`.
//! `run_block` dispatches on `z.pc`.

use std::fmt::Write;

use crate::analysis::{Analysis, Block, BlockInstr, Exit};
use zx_core::{Addr, AluOp, BlockOp, Cond, Instr, Op8, Reg8, Reg16, RotOp};

pub struct Meta<'a> {
    pub name: &'a str,
    pub snapshot_sha1: &'a str,
    pub rom_sha1: Option<&'a str>,
}

pub fn generate(meta: &Meta, analysis: &Analysis) -> String {
    let mut out = String::new();
    let rom = meta
        .rom_sha1
        .map_or("None".to_string(), |s| format!("Some({s:?})"));
    let _ = write!(
        out,
        "// @generated by zx-recomp for {name}. Do not edit.\n\
         // Derived from a user-supplied game file: do not commit or distribute.\n\
         \n\
         use zx_runtime::prelude::*;\n\
         \n\
         pub const NAME: &str = {name:?};\n\
         pub const SNAPSHOT_SHA1: &str = {snap:?};\n\
         pub const ROM_SHA1: Option<&str> = {rom};\n\
         pub const BLOCKS: usize = {count};\n\
         \n",
        name = meta.name,
        snap = meta.snapshot_sha1,
        count = analysis.blocks.len(),
    );

    // Blocks are grouped into modules by address so rustc can compile them
    // in parallel codegen units.
    let module = |addr: u16| format!("m{:x}", addr >> 12);

    out.push_str("pub fn run_block(z: &mut Zx) -> bool {\n    match z.pc {\n");
    for b in &analysis.blocks {
        let _ = writeln!(
            out,
            "        0x{0:04x} => {1}::b_{0:04x}(z),",
            b.start,
            module(b.start)
        );
    }
    out.push_str("        _ => false,\n    }\n}\n");

    let mut current: Option<String> = None;
    for b in &analysis.blocks {
        let m = module(b.start);
        if current.as_ref() != Some(&m) {
            if current.is_some() {
                out.push_str("}\n");
            }
            let _ = write!(out, "\nmod {m} {{\nuse super::*;\n");
            current = Some(m);
        }
        emit_block(&mut out, b, analysis);
    }
    if current.is_some() {
        out.push_str("}\n");
    }
    out
}

fn emit_block(out: &mut String, b: &Block, analysis: &Analysis) {
    let _ = write!(out, "\npub(super) fn b_{:04x}(z: &mut Zx) -> bool {{\n", b.start);

    // Verify the code is unchanged. ROM can't change, so is never checked.
    let mut segments: Vec<(u16, Vec<u8>)> = Vec::new();
    for ins in b.instrs.iter().filter(|i| !i.interpret && (i.addr >= 0x4000 || !analysis.rom_loaded)) {
        let bytes: Vec<u8> = (0..ins.d.len as u16)
            .map(|i| analysis.image[ins.addr.wrapping_add(i) as usize])
            .collect();
        match segments.last_mut() {
            Some((start, seg)) if start.wrapping_add(seg.len() as u16) == ins.addr => {
                seg.extend(bytes)
            }
            _ => segments.push((ins.addr, bytes)),
        }
    }
    for (start, bytes) in &segments {
        let list: Vec<String> = bytes.iter().map(|b| format!("0x{b:02x}")).collect();
        let _ = writeln!(
            out,
            "    if !z.code_ok(0x{start:04x}, &[{}]) {{ return false; }}",
            list.join(", ")
        );
    }

    for (i, ins) in b.instrs.iter().enumerate() {
        let is_last = i + 1 == b.instrs.len();
        let bytes: Vec<String> = (0..ins.d.len as u16)
            .map(|i| format!("{:02x}", analysis.image[ins.addr.wrapping_add(i) as usize]))
            .collect();
        let _ = writeln!(out, "    // {:04x}  {:<12} {}", ins.addr, bytes.join(" "), ins.d.instr);
        let fall_on = matches!(b.exit, Exit::FallInto(_));
        let code = emit_instr(ins, is_last && fall_on);
        let _ = writeln!(out, "    {code}");
    }
    match b.exit {
        Exit::FallInto(next) => {
            let _ = writeln!(out, "    z.pc = 0x{next:04x};\n    true\n}}");
        }
        Exit::Terminated => out.push_str("}\n"),
    }
}

// --- operand expressions ----------------------------------------------------

fn r8(r: Reg8) -> &'static str {
    match r {
        Reg8::B => "z.b",
        Reg8::C => "z.c",
        Reg8::D => "z.d",
        Reg8::E => "z.e",
        Reg8::H => "z.h",
        Reg8::L => "z.l",
        Reg8::A => "z.a",
        Reg8::IXH => "z.ixh()",
        Reg8::IXL => "z.ixl()",
        Reg8::IYH => "z.iyh()",
        Reg8::IYL => "z.iyl()",
    }
}

fn set_r8(r: Reg8, v: &str) -> String {
    match r {
        Reg8::IXH => format!("z.set_ixh({v});"),
        Reg8::IXL => format!("z.set_ixl({v});"),
        Reg8::IYH => format!("z.set_iyh({v});"),
        Reg8::IYL => format!("z.set_iyl({v});"),
        _ => format!("{} = {v};", r8(r)),
    }
}

fn r16(r: Reg16) -> &'static str {
    match r {
        Reg16::BC => "z.bc()",
        Reg16::DE => "z.de()",
        Reg16::HL => "z.hl()",
        Reg16::SP => "z.sp",
        Reg16::AF => "z.af()",
        Reg16::IX => "z.ix",
        Reg16::IY => "z.iy",
    }
}

fn set_r16(r: Reg16, v: &str) -> String {
    match r {
        Reg16::BC => format!("z.set_bc({v});"),
        Reg16::DE => format!("z.set_de({v});"),
        Reg16::HL => format!("z.set_hl({v});"),
        Reg16::AF => format!("z.set_af({v});"),
        Reg16::SP => format!("z.sp = {v};"),
        Reg16::IX => format!("z.ix = {v};"),
        Reg16::IY => format!("z.iy = {v};"),
    }
}

fn addr(a: Addr) -> String {
    match a {
        Addr::BC => "z.bc()".into(),
        Addr::DE => "z.de()".into(),
        Addr::HL => "z.hl()".into(),
        Addr::Idx(i, d) => {
            let base = r16(i.reg16());
            if d < 0 {
                format!("{base}.wrapping_sub({})", -(d as i16))
            } else {
                format!("{base}.wrapping_add({d})")
            }
        }
        Addr::Abs(nn) => format!("0x{nn:04x}"),
    }
}

fn get8(o: Op8) -> String {
    match o {
        Op8::Reg(r) => r8(r).into(),
        Op8::Mem(a) => format!("z.read({})", addr(a)),
        Op8::Imm(n) => format!("0x{n:02x}"),
    }
}

fn set8(o: Op8, v: &str) -> String {
    match o {
        Op8::Reg(r) => set_r8(r, v),
        Op8::Mem(a) => format!("z.write({}, {v});", addr(a)),
        Op8::Imm(_) => unreachable!("store to immediate"),
    }
}

/// Read-modify-write of an operand; `f` maps the old value expression to
/// the new one. Leaves the new value in `v`.
fn rmw(o: Op8, f: impl Fn(&str) -> String) -> String {
    match o {
        Op8::Mem(a) => format!("let a = {}; let v = {}; z.write(a, v);", addr(a), f("z.read(a)")),
        Op8::Reg(r) => format!("let v = {}; {}", f(r8(r)), set_r8(r, "v")),
        Op8::Imm(_) => unreachable!("modify immediate"),
    }
}

fn cond(c: Cond) -> &'static str {
    match c {
        Cond::NZ => "z.f & ZF == 0",
        Cond::Z => "z.f & ZF != 0",
        Cond::NC => "z.f & CF == 0",
        Cond::C => "z.f & CF != 0",
        Cond::PO => "z.f & PF == 0",
        Cond::PE => "z.f & PF != 0",
        Cond::P => "z.f & SF == 0",
        Cond::M => "z.f & SF != 0",
    }
}

fn alu_fn(op: AluOp) -> &'static str {
    match op {
        AluOp::Add => "alu_add",
        AluOp::Adc => "alu_adc",
        AluOp::Sub => "alu_sub",
        AluOp::Sbc => "alu_sbc",
        AluOp::And => "alu_and",
        AluOp::Xor => "alu_xor",
        AluOp::Or => "alu_or",
        AluOp::Cp => "alu_cp",
    }
}

fn rot_fn(op: RotOp) -> &'static str {
    match op {
        RotOp::Rlc => "rlc",
        RotOp::Rrc => "rrc",
        RotOp::Rl => "rl",
        RotOp::Rr => "rr",
        RotOp::Sla => "sla",
        RotOp::Sra => "sra",
        RotOp::Sll => "sll",
        RotOp::Srl => "srl",
    }
}

fn block_fn(op: BlockOp) -> &'static str {
    match op.step_op() {
        BlockOp::Ldi => "ldi",
        BlockOp::Ldd => "ldd",
        BlockOp::Cpi => "cpi",
        BlockOp::Cpd => "cpd",
        BlockOp::Ini => "ini",
        BlockOp::Ind => "ind",
        BlockOp::Outi => "outi",
        _ => "outd",
    }
}

fn jump(target: &str) -> String {
    format!("z.pc = {target}; return true;")
}

/// Rust statements for one instruction. `last_before_fallthrough` is set for
/// the final instruction of a block that runs on into another block.
fn emit_instr(ins: &BlockInstr, last_before_fallthrough: bool) -> String {
    use Instr::*;
    let d = &ins.d;
    let pc = ins.addr;
    let next = pc.wrapping_add(d.len as u16);
    let next_s = format!("0x{next:04x}");

    if ins.interpret {
        let resume = match d.instr.flow() {
            zx_core::Flow::Next | zx_core::Flow::Branch(_) => {
                format!("if z.pc != {next_s} || z.halted {{ return true; }}")
            }
            zx_core::Flow::Call { conditional: true, .. }
            | zx_core::Flow::Return { conditional: true } => {
                format!("if z.pc != {next_s} {{ return true; }}")
            }
            _ => "return true;".into(),
        };
        return format!("z.pc = 0x{pc:04x}; zx_runtime::interp::step(z); {resume} // self-modifying");
    }

    let body = match d.instr {
        Nop => String::new(),
        Halt => format!("z.halted = true; {}", jump(&next_s)),
        Di => "z.di();".into(),
        Ei if last_before_fallthrough => "z.ei(); z.ei_delay = true;".into(),
        Ei => "z.ei();".into(),
        Ld8(dst, src) => set8(dst, &get8(src)),
        Ld16(r, nn) => set_r16(r, &format!("0x{nn:04x}")),
        Ld16Load(r, a) => set_r16(r, &format!("z.read16(0x{a:04x})")),
        Ld16Store(a, r) => format!("z.write16(0x{a:04x}, {});", r16(r)),
        LdSp(r) => format!("z.sp = {};", r16(r)),
        Push(r) => format!("z.push({});", r16(r)),
        Pop(r) => format!("let v = z.pop(); {}", set_r16(r, "v")),
        ExDeHl => "z.ex_de_hl();".into(),
        ExAf => "z.ex_af();".into(),
        Exx => "z.exx();".into(),
        ExSp(r) => format!(
            "let v = z.read16(z.sp); z.write16(z.sp, {}); {}",
            r16(r),
            set_r16(r, "v")
        ),
        Alu(op, src) => format!("z.{}({});", alu_fn(op), get8(src)),
        Inc8(o) => rmw(o, |x| format!("z.inc8({x})")),
        Dec8(o) => rmw(o, |x| format!("z.dec8({x})")),
        Inc16(r) => set_r16(r, &format!("{}.wrapping_add(1)", r16(r))),
        Dec16(r) => set_r16(r, &format!("{}.wrapping_sub(1)", r16(r))),
        Add16(dst, src) => format!(
            "let v = z.add16({}, {}); {}",
            r16(dst),
            r16(src),
            set_r16(dst, "v")
        ),
        Adc16(r) => format!("z.adc_hl({});", r16(r)),
        Sbc16(r) => format!("z.sbc_hl({});", r16(r)),
        Daa => "z.daa();".into(),
        Cpl => "z.cpl();".into(),
        Neg => "z.neg();".into(),
        Ccf => "z.ccf();".into(),
        Scf => "z.scf();".into(),
        Rlca => "z.rlca();".into(),
        Rrca => "z.rrca();".into(),
        Rla => "z.rla();".into(),
        Rra => "z.rra();".into(),
        Rld => "z.rld();".into(),
        Rrd => "z.rrd();".into(),
        Rot(op, o, copy) => {
            let mut s = rmw(o, |x| format!("z.{}({x})", rot_fn(op)));
            if let Some(r) = copy {
                s = format!("{s} {}", set_r8(r, "v"));
            }
            s
        }
        Bit(n, o) => format!("z.bit({n}, {});", get8(o)),
        Res(n, o, copy) | Set(n, o, copy) => {
            let f = |x: &str| match d.instr {
                Res(..) => format!("{x} & 0x{:02x}", !(1u8 << n)),
                _ => format!("{x} | 0x{:02x}", 1u8 << n),
            };
            let mut s = rmw(o, f);
            if let Some(r) = copy {
                s = format!("{s} {}", set_r8(r, "v"));
            }
            s
        }
        Jp(None, a) | Jr(None, a) => jump(&format!("0x{a:04x}")),
        Jp(Some(c), a) => format!("if {} {{ {} }}", cond(c), jump(&format!("0x{a:04x}"))),
        Jr(Some(c), a) => format!(
            "if {} {{ z.t += {}; {} }}",
            cond(c),
            d.t_extra,
            jump(&format!("0x{a:04x}"))
        ),
        Djnz(a) => format!(
            "z.b = z.b.wrapping_sub(1); if z.b != 0 {{ z.t += {}; {} }}",
            d.t_extra,
            jump(&format!("0x{a:04x}"))
        ),
        Call(None, a) => format!("z.push({next_s}); {}", jump(&format!("0x{a:04x}"))),
        Call(Some(c), a) => format!(
            "if {} {{ z.t += {}; z.push({next_s}); {} }}",
            cond(c),
            d.t_extra,
            jump(&format!("0x{a:04x}"))
        ),
        Ret(None) => jump("z.pop()"),
        Ret(Some(c)) => format!("if {} {{ z.t += {}; {} }}", cond(c), d.t_extra, jump("z.pop()")),
        Reti | Retn => format!("z.iff1 = z.iff2; {}", jump("z.pop()")),
        Rst(n) => format!("z.push({next_s}); {}", jump(&format!("0x{n:04x}"))),
        JpInd(r) => jump(r16(r)),
        InA(n) => format!("z.a = z.port_in((z.a as u16) << 8 | 0x{n:02x});"),
        InC(r) => {
            let set = r.map_or(String::new(), |r| set_r8(r, "v"));
            format!("let v = z.port_in(z.bc()); z.in_flags(v); {set}")
        }
        OutA(n) => format!("z.port_out((z.a as u16) << 8 | 0x{n:02x}, z.a);"),
        OutC(r) => format!("z.port_out(z.bc(), {});", r.map_or("0", r8)),
        Block(op) if op.repeats() => format!(
            "while z.{}() {{ z.t += {}; if z.t >= FRAME_T {{ {} }} z.step({}, {}); }}",
            block_fn(op),
            d.t_extra,
            jump(&format!("0x{pc:04x}")),
            d.t,
            d.m1
        ),
        Block(op) => format!("z.{}();", block_fn(op)),
        Im(m) => format!("z.im = {m};"),
        LdIA => "z.i = z.a;".into(),
        LdRA => "z.r = z.a;".into(),
        LdAI => "z.ld_a_i();".into(),
        LdAR => "z.ld_a_r();".into(),
    };

    let step = format!("z.step({}, {});", d.t, d.m1);
    if body.is_empty() {
        step
    } else if body.contains("let ") {
        format!("{step} {{ {body} }}")
    } else {
        format!("{step} {body}")
    }
}
